package com.example.madfinalproject.reports;

import com.example.madfinalproject.coach.CoachProfile;
import com.example.madfinalproject.coach.PracticePlan;
import com.example.madfinalproject.coach.WeeklyReview;
import com.example.madfinalproject.utils.LogUtils;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public final class AICoachService {
    public List<String> personalizedAdvice(InterviewReport report){List<String> advice=new ArrayList<>();for(Map.Entry<String,Integer> item:report.categoryScores.entrySet())if(item.getValue()<60)advice.add("Practice "+item.getKey()+" answers and include specific supporting details.");if(report.missingKeywords.size()>report.matchedKeywords.size())advice.add("Use the missing interview keywords naturally, without memorizing scripted answers.");if(report.confidenceScore<14)advice.add("Practice concise answers aloud to improve confidence and delivery.");if(report.riskDetected)advice.add("Review risky statements and keep your visa intent factual, temporary, and consistent with your documents.");if(advice.isEmpty())advice.add("Maintain your strong performance and practice harder follow-up questions in your lowest-scoring category.");return advice.subList(0,Math.min(5,advice.size()));}
    public String summary(InterviewReport report){String strength=report.strongAreas.isEmpty()?"communication":report.strongAreas.get(0);String weakness=report.weakAreas.isEmpty()?"adding more specific detail":report.weakAreas.get(0).toLowerCase();return "You demonstrate strength in "+strength.toLowerCase()+". Your biggest improvement opportunity is "+weakness+".";}
    public void generateAndCache(InterviewReport report,Analytics analytics,List<InterviewReport> history){PracticePlan plan=practicePlan(report);CoachProfile profile=profile(report,analytics,history);WeeklyReview review=weekly(report,analytics);String uid=FirebaseAuth.getInstance().getUid();if(uid==null)uid="guest";FirebaseFirestore db=FirebaseFirestore.getInstance();save(db,"userPracticePlan",uid,plan,"Practice plan generated");save(db,"userReadiness",uid,profile,"Readiness updated");save(db,"userCoach",uid,profile,"Personalized coach updated");save(db,"userWeeklyReview",uid,review,"Weekly review updated");Map<String,Object>a=new HashMap<>();a.put("badges",profile.achievements);a.put("updatedAt",FieldValue.serverTimestamp());db.collection("userAchievements").document(uid).set(a).addOnSuccessListener(v->LogUtils.d("VisaCoach","Achievements earned: "+profile.achievements));}
    public PracticePlan practicePlan(InterviewReport r){PracticePlan p=new PracticePlan();p.categoriesToImprove.addAll(r.weakAreas);p.questionsToPractice.addAll(r.questions.subList(0,Math.min(5,r.questions.size())));String focus=p.categoriesToImprove.isEmpty()?"visa intent":p.categoriesToImprove.get(0);p.today="Practice two "+focus+" answers aloud and review missing keywords.";p.tomorrow="Repeat difficult bookmarked questions and improve answer specificity.";p.weeklyGoal="Complete 3 focused practices and one full mock interview.";p.estimatedStudyMinutes=Math.max(20,Math.min(60,20+p.categoriesToImprove.size()*5));return p;}
    public CoachProfile profile(InterviewReport r,Analytics a,List<InterviewReport>history){CoachProfile p=new CoachProfile();int consistency=a.totalInterviews>=5?100:a.totalInterviews*20;p.readinessScore=Math.round((r.grammarScore+r.confidenceScore+r.contentScore+r.visaIntentScore+r.overallScore+consistency)/6f);p.readinessLevel=p.readinessScore>=85?"Interview Ready":p.readinessScore>=70?"Advanced":p.readinessScore>=50?"Intermediate":"Beginner";p.confidenceTrend=trend(history,true);p.grammarProgress=trend(history,false);int words=0;Set<String>unique=new HashSet<>();Map<String,Integer>frequency=new HashMap<>();for(String answer:r.answers)for(String raw:answer.toLowerCase().split("[^a-z]+"))if(raw.length()>2){words++;unique.add(raw);frequency.put(raw,frequency.getOrDefault(raw,0)+1);}p.averageAnswerWords=r.answers.isEmpty()?0:words/r.answers.size();p.speakingSpeedWpm=r.durationMillis<=0?0:Math.round(words/(r.durationMillis/60000f));p.vocabularyVariety=words==0?0:Math.round(unique.size()*100f/words);p.keywordCoverage=r.keywordCoverage;p.answerCompleteness=Math.round((r.contentScore+r.keywordCoverage)/2f);p.personalizedTips.addAll(r.aiSuggestions);p.smartRevision.addAll(r.weakAreas);for(Map.Entry<String,Integer>e:frequency.entrySet())if(e.getValue()>=4&&!Arrays.asList("the","and","this","that","because").contains(e.getKey()))p.vocabularySuggestions.add("Replace repeated word '"+e.getKey()+"' with a precise context-specific alternative.");if(p.vocabularySuggestions.isEmpty())p.vocabularySuggestions.add("Use specific academic, financial, and career vocabulary from your own documents.");p.achievements.addAll(r.achievements);if(a.totalInterviews>=5)p.achievements.add("Five Interviews");if(r.categoryScores.containsKey("Finance")&&r.categoryScores.get("Finance")>=90)p.achievements.add("Excellent Finance Answers");return p;}
    public WeeklyReview weekly(InterviewReport r,Analytics a){WeeklyReview w=new WeeklyReview();w.overallProgress=a.averageScore;w.mostImprovedSkill=a.mostImprovedCategory;w.weakestSkill=a.weakestCategory;w.recommendedFocus=r.weakAreas.isEmpty()?"Maintain full-interview practice":r.weakAreas.get(0);w.coachMessage=r.aiSummary;return w;}
    private String trend(List<InterviewReport>h,boolean confidence){if(h.size()<2)return "Stable";int first=confidence?h.get(0).confidenceScore:h.get(0).grammarScore,last=confidence?h.get(h.size()-1).confidenceScore:h.get(h.size()-1).grammarScore;return last-first>=3?"Improving":first-last>=3?"Declining":"Stable";}
    private void save(FirebaseFirestore db,String collection,String uid,Object value,String log){Map<String,Object>map=new Gson().fromJson(new Gson().toJson(value),Map.class);map.put("updatedAt",FieldValue.serverTimestamp());db.collection(collection).document(uid).set(map).addOnSuccessListener(v->LogUtils.d("VisaCoach",log)).addOnFailureListener(e->LogUtils.e("VisaCoach",collection+" save failed",e));}
}
