package com.example.madfinalproject.reports;

import com.example.madfinalproject.ai.EvaluationSessionStore;
import com.example.madfinalproject.ai.models.AIEvaluationResponse;
import com.example.madfinalproject.ai.models.Scores;
import com.example.madfinalproject.utils.LogUtils;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public final class InterviewReportService {
    private static final String TAG="InterviewReports";
    private static final InterviewReportService INSTANCE=new InterviewReportService();
    private final FirebaseFirestore db=FirebaseFirestore.getInstance(); private final Gson gson=new Gson();
    public interface Callback { void onReady(InterviewReport report); void onError(String message); }
    public static InterviewReportService getInstance(){return INSTANCE;}

    public void generateAndSave(String country,long duration,Callback callback){InterviewReport report=generate(country,duration);ReportStore.set(report);Map<String,Object>data=gson.fromJson(gson.toJson(report),Map.class);data.put("type","report");data.put("timestamp",FieldValue.serverTimestamp());db.collection("userInterviewHistory").document(report.interviewId).set(data).addOnSuccessListener(v->{LogUtils.d(TAG,"Interview saved and report generated: "+report.interviewId);updateAnalytics(report);callback.onReady(report);}).addOnFailureListener(e->{LogUtils.e(TAG,"Report save failed",e);callback.onError("Report generated, but could not be saved. Check your connection.");});}

    private InterviewReport generate(String country,long duration){InterviewReport r=new InterviewReport();r.interviewId=UUID.randomUUID().toString();r.userId=userId();r.country=country;r.interviewDate=System.currentTimeMillis();r.durationMillis=duration;List<EvaluationSessionStore.Record>records=EvaluationSessionStore.records();r.questionsAnswered=records.size();int total=0,content=0,grammar=0,fluency=0,confidence=0;Map<String,List<Integer>>categories=new LinkedHashMap<>();for(EvaluationSessionStore.Record record:records){AIEvaluationResponse e=record.response;Scores s=e.getScores();total+=e.getOverallScore();content+=s.getContent();grammar+=s.getGrammar();fluency+=s.getFluency();confidence+=s.getConfidence();r.questions.add(record.request.getQuestion());r.answers.add(record.request.getUserAnswer());r.feedback.addAll(e.getFeedback());r.matchedKeywords.addAll(e.getMatchedKeywords());r.missingKeywords.addAll(e.getMissingKeywords());if(e.isRiskDetected()){r.riskDetected=true;r.riskyStatements.add(e.getRiskReason());}categories.computeIfAbsent(record.request.getCategory(),k->new ArrayList<>()).add(e.getOverallScore());}int n=Math.max(1,records.size());r.overallScore=total/n;r.contentScore=Math.round((content/(float)n)/40f*100);r.grammarScore=Math.round((grammar/(float)n)/20f*100);r.fluencyScore=Math.round((fluency/(float)n)/20f*100);r.confidenceScore=Math.round((confidence/(float)n)/20f*100);r.visaIntentScore=r.riskDetected?Math.max(0,r.overallScore-20):r.overallScore;int keywordTotal=r.matchedKeywords.size()+r.missingKeywords.size();r.keywordCoverage=keywordTotal==0?0:Math.round(r.matchedKeywords.size()*100f/keywordTotal);for(Map.Entry<String,List<Integer>>entry:categories.entrySet()){int sum=0;for(int score:entry.getValue())sum+=score;r.categoryScores.put(entry.getKey(),sum/entry.getValue().size());}r.grade=grade(r.overallScore);detectAreas(r);r.aiSuggestions=new AICoachService().personalizedAdvice(r);r.recommendedPractice.addAll(r.weakAreas);r.aiSummary=new AICoachService().summary(r);r.achievements.add("First Interview");if(r.overallScore>=80)r.achievements.add("Score Above 80");if(r.grammarScore>=90)r.achievements.add("Excellent Grammar");if(r.confidenceScore>=90)r.achievements.add("Confident Speaker");LogUtils.d(TAG,"Report generated");return r;}
    private void detectAreas(InterviewReport r){Map<String,Integer>metrics=new LinkedHashMap<>();metrics.put("Content",r.contentScore);metrics.put("Grammar",r.grammarScore);metrics.put("Fluency",r.fluencyScore);metrics.put("Confidence",r.confidenceScore);metrics.put("Keyword Coverage",r.keywordCoverage);List<Map.Entry<String,Integer>>values=new ArrayList<>(metrics.entrySet());values.sort((a,b)->b.getValue()-a.getValue());for(Map.Entry<String,Integer>v:values)if(v.getValue()>=70&&r.strongAreas.size()<5)r.strongAreas.add("Strong "+v.getKey());for(Map.Entry<String,Integer>v:values)if(v.getValue()<70)r.weakAreas.add(v.getKey());for(Map.Entry<String,Integer>v:r.categoryScores.entrySet())if(v.getValue()<60)r.weakAreas.add(v.getKey());if(r.weakAreas.isEmpty())r.weakAreas.add(values.get(values.size()-1).getKey());}
    private void updateAnalytics(InterviewReport latest){db.collection("userInterviewHistory").whereEqualTo("userId",latest.userId).get().addOnSuccessListener(snapshot->{List<InterviewReport>reports=new ArrayList<>();for(DocumentSnapshot d:snapshot.getDocuments())if("report".equals(d.getString("type"))){InterviewReport value=gson.fromJson(gson.toJson(d.getData()),InterviewReport.class);reports.add(value);}reports.sort(java.util.Comparator.comparingLong(r->r.interviewDate));Analytics a=calculate(reports);Map<String,Object>map=gson.fromJson(gson.toJson(a),Map.class);map.put("updatedAt",FieldValue.serverTimestamp());db.collection("userAnalytics").document(latest.userId).set(map);db.collection("userProgress").document(latest.userId).set(map);Map<String,Object>practice=new HashMap<>();practice.put("categories",latest.recommendedPractice);practice.put("updatedAt",FieldValue.serverTimestamp());db.collection("recommendedPractice").document(latest.userId).set(practice);new AICoachService().generateAndCache(latest,a,reports);LogUtils.d(TAG,"Analytics updated; achievements earned: "+latest.achievements);}).addOnFailureListener(e->LogUtils.e(TAG,"Analytics update failed",e));}
    public Analytics calculate(List<InterviewReport>reports){Analytics a=new Analytics();if(reports.isEmpty())return a;int sum=0;a.highestScore=0;a.lowestScore=100;Map<String,List<Integer>>countries=new HashMap<>(),categories=new HashMap<>();for(InterviewReport r:reports){sum+=r.overallScore;a.highestScore=Math.max(a.highestScore,r.overallScore);a.lowestScore=Math.min(a.lowestScore,r.overallScore);a.totalPracticeTimeMillis+=r.durationMillis;a.weeklyScores.add(r.overallScore);countries.computeIfAbsent(r.country,k->new ArrayList<>()).add(r.overallScore);for(Map.Entry<String,Integer>e:r.categoryScores.entrySet())categories.computeIfAbsent(e.getKey(),k->new ArrayList<>()).add(e.getValue());}a.totalInterviews=reports.size();a.averageScore=sum/reports.size();a.bestCountry=best(countries,true);a.weakestCategory=best(categories,false);a.mostImprovedCategory=improved(categories);a.streak=Math.min(7,reports.size());if(a.weeklyScores.size()>7)a.weeklyScores=new ArrayList<>(a.weeklyScores.subList(a.weeklyScores.size()-7,a.weeklyScores.size()));a.monthlyScores=new ArrayList<>(a.weeklyScores);return a;}
    private String best(Map<String,List<Integer>>values,boolean highest){String name="";int chosen=highest?-1:101;for(Map.Entry<String,List<Integer>>e:values.entrySet()){int sum=0;for(int v:e.getValue())sum+=v;int avg=sum/e.getValue().size();if((highest&&avg>chosen)||(!highest&&avg<chosen)){chosen=avg;name=e.getKey();}}return name;}
    private String improved(Map<String,List<Integer>>values){String name="";int delta=Integer.MIN_VALUE;for(Map.Entry<String,List<Integer>>e:values.entrySet())if(e.getValue().size()>1){int d=e.getValue().get(e.getValue().size()-1)-e.getValue().get(0);if(d>delta){delta=d;name=e.getKey();}}return name;}
    private String grade(int score){return score>=90?"A+":score>=80?"A":score>=70?"B":score>=60?"C":"Needs Practice";}
    private String userId(){String uid=FirebaseAuth.getInstance().getUid();return uid==null?"guest":uid;}
}
